apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "Defines AWS-specific configuration for EC2 instances launched by Karpenter"
spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: "karpenter-node-role"

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName | quote }}

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true

  tags:
    Environment: production
    ManagedBy: Karpenter
    Cluster: {{ .Values.clusterName | quote }}

