apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-secrets
  namespace: argocd
  annotations:
    kubernetes.io/description: "Applies the ClusterSecretStore and application-level ExternalSecrets"
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: HEAD
    path: k8s/secrets
    helm:
      parameters:
        - name: awsRegion
          value: {{ .Values.awsRegion | quote }}
        - name: clusterName
          value: {{ .Values.clusterName | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
