apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    kubernetes.io/description: "Installs External Secrets Operator to sync secrets from AWS Secrets Manager to Kubernetes"
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.10.9"
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: serviceAccount.create
          value: "false"
        - name: serviceAccount.name
          value: "external-secrets"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
