apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    kubernetes.io/description: "Configures cluster-wide access for the External Secrets Operator to read secrets from AWS Secrets Manager"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | quote }}
