apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-api-key
  namespace: fastapi
  annotations:
    kubernetes.io/description: "Defines the mapping and sync parameters for pulling the GOOGLE_API_KEY secret from AWS into the fastapi namespace"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: google-api-key
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: {{ printf "%s/GOOGLE_API_KEY" .Values.clusterName | quote }}
        property: GOOGLE_API_KEY
