apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${GIT_REPOSITORY_URL}
    targetRevision: HEAD
    path: k8s/argocd/apps
    helm:
      parameters:
        - name: repoURL
          value: ${GIT_REPOSITORY_URL}
        - name: clusterName
          value: ${CLUSTER_NAME}
        - name: awsRegion
          value: ${AWS_REGION}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
